### ISSUE TITLE
The MAE's minimum value

### ISSUE THREAD

**Issue by Tomasyao77** [yu4u/age-estimation-pytorch#8]
Thanks to the excellent code of the blogger, I trained 80epoch with your code on GPU GTX 1080ti, but my mae minimum is 4.144, and your mae dropped to 3.9 at 44epoch. Is my luck bad? Is this mae related to computing power, or is it random with every training?Thank you very much！

**Comment by yu4u** [comment]
I did not check the variance of MAE, but I think it depends on random seeds...
